### ISSUE TITLE
The values of FoF_MaxGals and MaxGals

### ISSUE THREAD

**Issue by diyiliaoya** [darrencroton/sage#5]
Hi Darren,

In load_tree() function, you both set MaxGals and FoF_MaxGals to 10000.
Why 10000? Is there any particular reason?

Cheers,
Shijie

**Comment by darrencroton** [comment]
Basically to set up the structures/arrays and for memory. You can change this to whatever is reasonable for your simulation(s). Usually best to set it lower so you're not wasting resources, to the degree that you can.

**Comment by diyiliaoya** [comment]
Got it! Thank you!

**Comment by darrencroton** [comment]
No problem. Good luck!

**Comment by manodeep** [comment]
A note that you can set `FoF_MaxGals` to a lower value; and if more memory is required, the code will re-allocate in increments of 10000. This was added in pull request #4 (commit 0ca9ce12b87742c6228da898fe693ceb0cce1c6f, in `core_build_model.c`)

**Comment by darrencroton** [comment]
Based on the above discussion, i'll close this issue. Let me know if that's not ok @diyiliaoya .
