### ISSUE TITLE
the number of output galaxies 

### ISSUE THREAD

**Issue by diyiliaoya** [darrencroton/sage#6]
Hi Darren,

I found that not all the type1 galaxies are saved in the output. I tried two different simulations, there
are always many type1 galaxies are not be saved. I wonder what cause this?
Thank you!

**Comment by darrencroton** [comment]
Can you provide more details. 

- What simulations did you use? If not Millennium, how were the trees constructed and are you sure they're compatible with SAGE? (I can help with such tree conversions if you contact me via email)
- Can you confirm the galaxies not being saved haven't already merged or removed during the time step? 
- Can you check the sub-halo of the galaxy and make sure it's still in the tree and that the galaxy/subhalo isn't right at the resolution limit (where sometimes strange things can happen)?

Thanks.

**Comment by diyiliaoya** [comment]
I also test in Millennium. There should be 2657356 type1 galaxies, but SAGE only output 2424403 
galaxies. It is the z=0 snapshot. So the type1 galaxies shouldn't be merged or removed. And the subhalo still in the tree.

**Comment by darrencroton** [comment]
How do you know there should be 2657356 type 1 galaxies? Have you modified the code to count them just before writing the snapshot, then are comparing this number to what's actually in the output file? Or something else.

**Comment by diyiliaoya** [comment]
I didn't modify the code. I write a small code to read the merger tree and get the number of subhalos. There are 2657356 subhalos other than main halos in the z=0 snapshot. In the SAGE output file there are only 2424403 type1 galaxies, so I think some type1 galaxies are not saved.

**Comment by darrencroton** [comment]
Some satellites merge with their central or disrupt to the stellar halo before their subhalo is lost. See Croton et al. 2016 (https://arxiv.org/abs/1601.04709) for details of how the model is constructed. I'm happy to talk more about it if you want to email me (here is probably not the best place to talk model physics).

**Comment by diyiliaoya** [comment]
I think maybe I didn't totally get the essence of the paper and the code. I should read the paper
and the code again. I will email you if I still don't understand or get another problem.
Thank you for your time!

**Comment by darrencroton** [comment]
No problem. Happy to help.

**Comment by darrencroton** [comment]
Based on the above discussion, i'll close this issue. Hope that's ok @diyiliaoya .
